"""Sample a graph structure from GraphPFN's pretraining prior and plot it.

Uses the exact graph-generation distribution config from the pretraining run
(exp/graphpfn/pretrain/main/pretrain.toml): a `graph_then_attributes` prior
whose structure is generated by the multi-level SBM + preferential attachment
sampler described in Section 4.1 of the paper. Only the graph part of the
prior is sampled (no node features/targets), since we only need the structure.

Usage:
    uv run dev/sample_prior_graph.py --n-samples 4
    # or, inside an activated env:
    python dev/sample_prior_graph.py --n-samples 4
"""

import argparse
import random
import sys
import tomllib
from pathlib import Path

PAPER_DIR = Path(__file__).resolve().parent.parent
if str(PAPER_DIR) not in sys.path:
    sys.path.insert(0, str(PAPER_DIR))

import dgl  # noqa: E402
import matplotlib.pyplot as plt  # noqa: E402
import networkx as nx  # noqa: E402
import numpy as np  # noqa: E402
import torch  # noqa: E402

from lib.graphpfn.prior.config import sample_configs  # noqa: E402
from lib.graphpfn.prior.graphs import sample_graph  # noqa: E402

CONFIG_PATH = PAPER_DIR / "exp/graphpfn/pretrain/main/pretrain.toml"


def load_prior_distribution_config() -> dict:
    with open(CONFIG_PATH, "rb") as f:
        data = tomllib.load(f)
    return data["base_config"]["prior"]


def graph_stats(nx_graph: nx.Graph) -> dict:
    n = nx_graph.number_of_nodes()
    m = nx_graph.number_of_edges()
    avg_degree = 2 * m / n if n else 0.0
    clustering = nx.average_clustering(nx_graph)
    return {"n_nodes": n, "n_edges": m, "avg_degree": avg_degree, "clustering": clustering}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--n-samples", type=int, default=4)
    parser.add_argument(
        "--out",
        type=str,
        default=str(Path(__file__).parent / "graph_prior_samples.png"),
    )
    args = parser.parse_args()

    random.seed(args.seed)
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)

    dist_config = load_prior_distribution_config()

    n_cols = (args.n_samples + 1) // 2 if args.n_samples > 1 else 1
    n_rows = 2 if args.n_samples > 1 else 1
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(6 * n_cols, 6 * n_rows))
    axes = np.atleast_1d(axes).flatten()

    for i in range(args.n_samples):
        sampled_config = sample_configs(dist_config, batch_size=1)[0]
        graph_config = sampled_config["prior"]["graph"]

        graph = sample_graph(graph_config)
        # dgl.to_networkx returns a MultiDiGraph (parallel/reciprocal edges from
        # the undirected-as-directed representation); collapse to a simple
        # undirected Graph so clustering/layout algorithms work.
        nx_graph = nx.Graph(dgl.to_networkx(graph))

        stats = graph_stats(nx_graph)
        print(
            f"[sample {i}] sampler={graph_config['sampler']['_type_']} "
            f"requested_n_nodes={graph_config['n_nodes']} "
            f"requested_avg_degree={graph_config['avg_degree']:.1f} -> {stats}"
        )

        ax = axes[i]
        pos = nx.spring_layout(nx_graph, seed=args.seed, iterations=50)
        nx.draw_networkx_edges(nx_graph, pos, ax=ax, alpha=0.15, width=0.4, edge_color="gray")
        nx.draw_networkx_nodes(nx_graph, pos, ax=ax, node_size=6, node_color="crimson", linewidths=0)
        ax.set_axis_off()
        ax.set_title(
            f"n={stats['n_nodes']}, m={stats['n_edges']}, "
            f"avg_deg={stats['avg_degree']:.1f}, clustering={stats['clustering']:.2f}",
            fontsize=10,
        )

    for j in range(args.n_samples, len(axes)):
        axes[j].set_axis_off()

    fig.suptitle("Samples from the GraphPFN graph prior (multi-level SBM + PA)")
    fig.tight_layout()
    fig.savefig(args.out, dpi=150)
    print(f"Saved figure to {args.out}")


if __name__ == "__main__":
    main()
